name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  DATA_DIR: ./data/

permissions:
  contents: read

jobs:
  test:
    name: Test on ${{ matrix.os }} ${{ matrix.target }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path ./main/Cargo.toml --verbose
      - name: Download Roberta language files
        run: |
          ./scripts/download_lang_files.sh --verbose --dir ${DATA_DIR}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path ./main/Cargo.toml --verbose --all-features

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./main/Cargo.toml --all-targets --all-features  -- -D warnings
