name: Release

on:
  release:
    types: [published]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  DATA_DIR: ./data/

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ./main/Cargo.toml --verbose
      # Test the library one last time before packaging and publishing
      - name: Download Roberta language files
        run: |
          ./scripts/download_lang_files.sh --verbose --dir ${DATA_DIR}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --manifest-path ./main/Cargo.toml --verbose --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: package
          args: --manifest-path ./main/Cargo.toml --verbose
      - uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path ./main/Cargo.toml --verbose --token ${{ secrets.CRATES_IO_TOKEN }}
